#------------------------------------------------------------
# This config-file is only needed for development. Instead of changing
# the url everytime you work locally on the project, run a server with
# both configuration files:
#
#    jekyll serve --config _config.yml,_config_dev.yml
#------------------------------------------------------------

# Website domain (no trailing slash).
domain: "http://0.0.0.0:4000"

# Root.
root: "http://0.0.0.0:4000"
